export const REQUEST_COMMENTS = 'ducks/comments/RECEIVE_COMMENT_LIST';
export const RESPONSE_COMMENTS_SUCCESS = 'ducks/posts/RESPONSE_COMMENTS_SUCCESS';
export const RESPONSE_COMMENTS_FAILURE = 'ducks/posts/RESPONSE_COMMENTS_FAILURE';